-- Desativar temporariamente restrições de chaves estrangeiras (opcional, para simplificar)
-- ALTER SESSION SET CONSTRAINTS = DEFERRED;

-- Deletar registros em ordem para respeitar dependências
DELETE FROM DISTANCA_ARMAZEM_MAQUINA;
DELETE FROM ENCOMENDAS;
DELETE FROM DISTANCIA_MAQUINAS;
DELETE FROM RUPTURAS;
DELETE FROM PRODUTO_VIAGEM;
DELETE FROM VENDAS;
DELETE FROM REABASTECIMENTOS;
DELETE FROM MANUTENCAO;
DELETE FROM VISITAS;
DELETE FROM VIAGENS;
DELETE FROM ROTASDEFENIDAS;
DELETE FROM ROTAS;
DELETE FROM STOCK;
DELETE FROM COMPARTIMENTOS;
DELETE FROM PRODUTOS;
DELETE FROM VEICULOS;
DELETE FROM FUNCIONARIOS;
DELETE FROM MAQUINAS;
DELETE FROM ARMAZEM;

-- Confirmar as alterações
COMMIT;

-- DESABILITAR TODOS OS TRIGGERS E ATIVAR OS DE VERIFICAÇÂO
ALTER TRIGGER R_TRIG_2023144573 DISABLE;
ALTER TRIGGER R_TRIG_2023144551 DISABLE;
ALTER TRIGGER R_TRIG_2023144606 DISABLE;
ALTER TRIGGER UPDATE_STOCK DISABLE;
ALTER TRIGGER UPDATE_VIAGEM DISABLE;
ALTER TRIGGER ABASTECE DISABLE;



-- Inserir dados para testar funções, procedimentos e triggers

-- Armazéns
INSERT INTO ARMAZEM (ID_ARMAZEM, LOCALIZACAO, LATITUDE_A, LONGITUDE_A)
VALUES (1, 'Lisboa', 38.7223, -9.1393);
INSERT INTO ARMAZEM (ID_ARMAZEM, LOCALIZACAO, LATITUDE_A, LONGITUDE_A)
VALUES (2, 'Porto', 41.1579, -8.6291);

-- Máquinas
INSERT INTO MAQUINAS (ID_MAQUINA, LOCALIZACAO_MAQUINA, LATUTUDE, LONGITUDE, ESTADO_MAQUINA)
VALUES (1, 'Porto', 41.1579, -8.6291, 'ATIVA');
INSERT INTO MAQUINAS (ID_MAQUINA, LOCALIZACAO_MAQUINA, LATUTUDE, LONGITUDE, ESTADO_MAQUINA)
VALUES (2, 'Coimbra', 40.2033, -8.4103, 'ATIVA');


-- Produtos
INSERT INTO PRODUTOS (ID_PRODUTO, NOME_PRODUTO, REFERENCIA, TIPO_PRODUTO, PRECO_PRODUTO)
VALUES (1, 'Água', 'AGUA500', 'BEBIDA', 0.5);

INSERT INTO COMPARTIMENTOS (ID_COMPARTIMENTO, ID_MAQUINA, ID_PRODUTO, CAPACIDADE_MAXIMA, QUANTIDADE_COMPARTIMENTO, PRECO_COMPARTIMENTO, CODIGO)
VALUES (1, 1, 1, 100, 0, 1.5, 'AGUA500');
INSERT INTO COMPARTIMENTOS (ID_COMPARTIMENTO, ID_MAQUINA, ID_PRODUTO, CAPACIDADE_MAXIMA, QUANTIDADE_COMPARTIMENTO, PRECO_COMPARTIMENTO, CODIGO)
VALUES (2, 2, 1, 100, 0, 1.5, 'AGUA500');
-- Stock
INSERT INTO STOCK (ID_ARMAZEM, ID_PRODUTO, QUANTIDADE_EM_STOCK)
VALUES (1, 1, 2000);

-- Funcionários
INSERT INTO FUNCIONARIOS (ID_FUNCIONARIO)
VALUES (1);

-- Veículos
INSERT INTO VEICULOS (ID_VEICULO,ID_ARMAZEM,MATRICULA,AUTONOMIA_KM)
VALUES (1,1,'AB0129',200);

-- Rotas
INSERT INTO ROTAS (ID_ROTA, ID_ARMAZEM, NOME_ROTA, ROTAKM)
VALUES (1, 1, 'Rota1', 100);

-- Viagens
INSERT INTO VIAGENS (ID_VIAGEM, ID_ROTA, ID_FUNCIONARIO, DATA_INICIO_VIAGEM)
VALUES (1, 1, 1, SYSDATE);

-- Visitas
INSERT INTO VISITAS (ID_VISITA, ID_VIAGEM, ID_MAQUINA, DATA_HORA_CHEGADA, DATA_HORA_SAIDA)
VALUES (1, 1, 1, SYSDATE - 1/24, SYSDATE - 0.5/24);

-- Rotas Definidas
INSERT INTO ROTASDEFENIDAS (ID_MAQUINA, ID_ROTA, ORDEM)
VALUES (1, 1, 1);
INSERT INTO ROTASDEFENIDAS (ID_MAQUINA, ID_ROTA, ORDEM)
VALUES (2, 1, 2);


-- Produto Viagem
INSERT INTO PRODUTO_VIAGEM (ID_VIAGEM, ID_PRODUTO, QUANTIDADE_PV)
VALUES (1, 1, 1000);

-- Reabastecimentos


INSERT INTO REABASTECIMENTOS (ID_REABASTECIMENTO, ID_VISITA, ID_COMPARTIMENTO, ID_PRODUTO, QUANTIDADE_REABASTECIMENTO, DATA_HORA_REABASTECIMENTO)
VALUES (1, 1, 1, 1, 10, SYSDATE - 2);


-- vendas

INSERT INTO VENDAS (ID_VENDA, ID_COMPARTIMENTO, ID_PRODUTO, DATA_HORA_VENDA, METODO_PAGAMENTO, VALOR_PAGO)
VALUES (1, 1, 1, SYSDATE + 1, 'CREDITO', 1.5);
INSERT INTO VENDAS (ID_VENDA, ID_COMPARTIMENTO, ID_PRODUTO, DATA_HORA_VENDA, METODO_PAGAMENTO, VALOR_PAGO)
VALUES (2, 1, 1, SYSDATE + 2, 'CREDITO', 1.5);
INSERT INTO VENDAS (ID_VENDA, ID_COMPARTIMENTO, ID_PRODUTO, DATA_HORA_VENDA, METODO_PAGAMENTO, VALOR_PAGO)
VALUES (3, 1, 1, SYSDATE + 5, 'CREDITO', 1.5);


-- Rupturas
INSERT INTO RUPTURAS (ID_RUPTURA, DATA_HORA_RUPTURA)
VALUES (1, SYSDATE - 1);
INSERT INTO RUPTURAS (ID_RUPTURA, DATA_HORA_RUPTURA)
VALUES (2, SYSDATE);


ALTER TRIGGER R_TRIG_2023144573 ENABLE;
ALTER TRIGGER R_TRIG_2023144551 ENABLE;
ALTER TRIGGER R_TRIG_2023144606 ENABLE;
ALTER TRIGGER UPDATE_STOCK ENABLE;
ALTER TRIGGER UPDATE_VIAGEM ENABLE;
ALTER TRIGGER ABASTECE ENABLE;


