-- 1. Vista para Consultas
CREATE VIEW VISTA_CONSULTAS AS
SELECT 
    c.ID_CONSULTA_M AS ID_CONSULTA,
    c.DATA,
    c.HORA,
    u.NOME AS UTENTE,
    f.NOME AS DENTISTA,
    CASE 
        WHEN cr.ESTADO IS NOT NULL THEN cr.ESTADO
        ELSE 'MARCADA'
    END AS ESTADO
FROM 
    CONSULTAS_MARCADAS c
LEFT JOIN CONSULTAS_REALIZADAS cr ON c.ID_CONSULTA_M = cr.ID_CONSULTA
JOIN UTENTES u ON c.ID_UTENTE = u.ID_UTENTE
JOIN FUNCIONARIOS f ON c.ID_FUNCIONARIO = f.ID_FUNCIONARIO;


-- 2. Vista para Pagamentos e Faturação
CREATE VIEW VISTA_PAGAMENTOS_FATURAS AS
SELECT 
    f.ID_FATURA,
    f.DATA_EMISSAO,
    u.NOME AS UTENTE,
    f.METODO_PAGAMENTO,
    f.ESTADO,
    f.VALOR_TOTAL
FROM 
    FATURAS f
JOIN UTENTES u ON f.ID_UTENTE = u.ID_UTENTE;

-- 3. Vista para Funcionários
CREATE VIEW VISTA_FUNCIONARIOS AS
SELECT 
    f.ID_FUNCIONARIO,
    f.NOME,
    c.NOME_CARGO,
    d.ESPECIALIDADE
FROM 
    FUNCIONARIOS f
LEFT JOIN CARGOS c ON f.ID_CARGO = c.ID_CARGO
LEFT JOIN DENTISTA d ON f.ID_FUNCIONARIO = d.ID_FUNCIONARIO;

-- 4. Vista para Materiais e Fornecedores
CREATE VIEW VISTA_MATERIAIS_FORNECEDORES AS
SELECT 
    m.ID_MATERIAL,
    m.DESCRICAO,
    m.QUANTIDADE,
    f.NOME AS FORNECEDOR,
    f.LOCALIZACAO
FROM 
    MATERIAIS m
JOIN FORNECEDORES f ON m.ID_FORNECEDOR = f.ID_FORNECEDOR;

-- 5. Vista para Utentes
CREATE VIEW VISTA_UTENTES AS
SELECT 
    u.ID_UTENTE,
    u.NOME,
    u.DATA_NASCIMENTO,
    COUNT(c.ID_CONSULTA) AS TOTAL_CONSULTAS,
    MAX(f.DATA_EMISSAO) AS ULTIMA_FATURA
FROM 
    UTENTES u
LEFT JOIN CONSULTAS_REALIZADAS c ON u.ID_UTENTE = c.ID_UTENTE
LEFT JOIN FATURAS f ON u.ID_UTENTE = f.ID_UTENTE
GROUP BY 
    u.ID_UTENTE, u.NOME, u.DATA_NASCIMENTO;

